Workshop schreiben
pep-dortmund/homepage pull request #430
Opened 2022-02-01 11:24 UTC by marschmitz

### Checklist

- [ ] All included images are public domain images or their respective licenses are respected (e.g. attribution for CC-BY)
- [ ] Images are reduced to around 2000px at the long edge and in jpg format

2022-02-04 08:42 UTC, jpherdi requested changes

2022-02-04 08:42 UTC, jpherdi commented on _posts/2022/2022-02-01-workshop-schreiben.md
> +Anmelden könnt ihr euch bis zum 23.02.2022 unter [registration.pep-dortmund.org/events/](https://registration.pep-dortmund.org/events/9/registration/)
Der Event Link ist noch nicht der richtige oder? 
Da komm ich auf so eine Seite:
![image](https://user-images.githubusercontent.com/41512963/152498208-fc0bbb26-cbe9-4524-8a2f-9815b2984bb3.png)

2022-02-04 11:14 UTC, maxnoe commented on _posts/2022/2022-02-01-workshop-schreiben.md
> +Anmelden könnt ihr euch bis zum 23.02.2022 unter [registration.pep-dortmund.org/events/](https://registration.pep-dortmund.org/events/9/registration/)
Ja, es muss eine neue Veranstaltung im System erstellt werden und der Link dann hier rein

2022-02-05 00:25 UTC, jpherdi commented on _posts/2022/2022-02-01-workshop-schreiben.md
> +Anmelden könnt ihr euch bis zum 23.02.2022 unter [registration.pep-dortmund.org/events/](https://registration.pep-dortmund.org/events/9/registration/)
Das hab ich noch nie gemacht.
Wäre gut, wenn das recht schnell gemacht würde, da der Workshop laut Protokoll schon beworben wurde.

2022-02-06 11:54 UTC, jpherdi approved these changes

2022-02-06 11:56 UTC, maxnoe requested changes
Can we please change the font in the image to not be Comic Sans MS.

E.g. use Comic Neue or the XKCD font.

* http://comicneue.com/
* https://github.com/ipython/xkcd-font/blob/master/xkcd-script/font/xkcd-script.ttf

2022-02-06 11:56 UTC, maxnoe commented
Also, are we sure that we can use that image?

2022-02-06 12:25 UTC, maxnoe commented
Ok, found the base image, it's free to use even comercially without attribution: https://pixabay.com/de/illustrations/moses-prophet-schreiben-bart-2715485/

2022-02-06 12:25 UTC, maxnoe approved these changes

2022-02-06 12:25 UTC, merged