new jobboerse entries for deichmann and infineon
pep-dortmund/homepage pull request #580
Opened 2024-04-15 21:18 UTC by ToniAJ

### Checklist

pls check if everything (format etc.) looks alright (I couldn't control this by myself because of the jekyll command not working...)

2024-04-16 10:29 UTC, jpwgnr requested changes

2024-04-16 10:29 UTC, jpwgnr commented on jobboerse/_posts/2024-04-15-deichmann.md
> +* [Junior Digital Marketer Paid Social (m/w/d)](https://www.deichmann-karriere.de/jobs/2024-22907/?_gl=1*1e0sgx3*_up*MQ..*_ga*OTYyODE5NDYwLjE3MTMxNzQxMzg.*_ga_74BHZ6JW9K*MTcxMzE3NDEzOC4xLjAuMTcxMzE3N
Diese Links sehen super komisch aus, ist das so gewollt?

2024-04-16 10:44 UTC, maxnoe commented on jobboerse/_posts/2024-04-15-deichmann.md
> +* [Junior Digital Marketer Paid Social (m/w/d)](https://www.deichmann-karriere.de/jobs/2024-22907/?_gl=1*1e0sgx3*_up*MQ..*_ga*OTYyODE5NDYwLjE3MTMxNzQxMzg.*_ga_74BHZ6JW9K*MTcxMzE3NDEzOC4xLjAuMTcxMzE3N
Der query string kann weg: `https://www.deichmann-karriere.de/jobs/2024-22907/`

2024-04-16 10:45 UTC, maxnoe commented on jobboerse/_posts/2024-04-15-deichmann.md
> +* [Junior Digital Marketer Paid Social (m/w/d)](https://www.deichmann-karriere.de/jobs/2024-22907/?_gl=1*1e0sgx3*_up*MQ..*_ga*OTYyODE5NDYwLjE3MTMxNzQxMzg.*_ga_74BHZ6JW9K*MTcxMzE3NDEzOC4xLjAuMTcxMzE3N
Das ist ein cross-domain tracking ding von google analytics, sollten wir nicht übernehmen

2024-04-17 11:47 UTC, jpwgnr approved these changes

2024-04-17 11:47 UTC, merged